spring.application.name=parking-control-api
spring.datasource.url=jdbc:mysql://localhost:3306/parking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8088
